### ISSUE TITLE
Difference between `K.identity(self.embeddings)` and `self.embeddings + 0.0`

### ISSUE THREAD

**Issue by Owen864720655** [CyberZHG/keras-embed-sim#3]
Hi author,

You have two commits to change between `K.identity(self.embeddings)` and `self.embeddings + 0.0`. It seems to me that they both use a deepcopy to duplicate `self.embeddings`.

Could you explain their difference?

Thanks!

**Comment by CyberZHG** [comment]
Why used `identity`: the layer will not be built correctly if you return the input directly.
Why replaced with `+ 0.0`: TensorFlow removed `identity`.

**Comment by Owen864720655** [comment]
Not clear. Could you explain more?

**Comment by CyberZHG** [comment]
> Not clear. Could you explain more?

They are the same. You don't have `identity` after `tf-2.0`, therefore it's replaced with a manual implementation.

**Comment by Owen864720655** [comment]
Thanks a lot!
